development:
  adapter: postgresql
  database: friend420_development
  username: 
  password: 
  hostname: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: friend420_test
  username: psql
  password: 1234
  hostname: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: friend420_production
  pool: 5
  timeout: 5000

